-- V90.fy: Performance engineering, load/stress validation and scalability controls.
CREATE TABLE IF NOT EXISTS erp_perf_threshold(perf_threshold_id TEXT PRIMARY KEY,organization_id TEXT NULL,metric_code TEXT NOT NULL,warning_threshold DOUBLE PRECISION NOT NULL,fail_threshold DOUBLE PRECISION NOT NULL,direction TEXT NOT NULL,evidence_ref TEXT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,metric_code));
CREATE TABLE IF NOT EXISTS erp_perf_baseline(baseline_id TEXT PRIMARY KEY,organization_id TEXT NULL,endpoint TEXT NOT NULL,environment TEXT NOT NULL,p50_ms DOUBLE PRECISION NOT NULL,p95_ms DOUBLE PRECISION NOT NULL,p99_ms DOUBLE PRECISION NOT NULL,throughput_rps DOUBLE PRECISION NOT NULL,error_rate_pct DOUBLE PRECISION NOT NULL,concurrency INTEGER NOT NULL,result TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_load_run(load_run_id TEXT PRIMARY KEY,organization_id TEXT NULL,scenario TEXT NOT NULL,environment TEXT NOT NULL,concurrency INTEGER NOT NULL,duration_seconds INTEGER NOT NULL,requests INTEGER NOT NULL,failures INTEGER NOT NULL,p95_ms DOUBLE PRECISION NOT NULL,throughput_rps DOUBLE PRECISION NOT NULL,error_rate_pct DOUBLE PRECISION NOT NULL,result TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_hotspot(hotspot_id TEXT PRIMARY KEY,organization_id TEXT NULL,query_fingerprint TEXT NOT NULL,duration_ms DOUBLE PRECISION NOT NULL,calls INTEGER NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL,evidence_ref TEXT NULL,remediation_note TEXT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_capacity(capacity_id TEXT PRIMARY KEY,organization_id TEXT NULL,environment TEXT NOT NULL,cpu_utilization_pct DOUBLE PRECISION NULL,memory_utilization_pct DOUBLE PRECISION NULL,db_connections INTEGER NULL,db_connection_limit INTEGER NULL,worker_count INTEGER NULL,worker_limit INTEGER NULL,result TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_regression(regression_id TEXT PRIMARY KEY,organization_id TEXT NULL,comparison_name TEXT NOT NULL,baseline_ref TEXT NOT NULL,current_ref TEXT NOT NULL,latency_delta_pct DOUBLE PRECISION NOT NULL,throughput_delta_pct DOUBLE PRECISION NOT NULL,error_rate_delta_pct DOUBLE PRECISION NOT NULL,result TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_period_close(close_id TEXT PRIMARY KEY,organization_id TEXT NULL,period_key TEXT NOT NULL,signoff_note TEXT NOT NULL,evidence_ref TEXT NOT NULL,closed_by TEXT NOT NULL,closed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,period_key));
CREATE INDEX IF NOT EXISTS ix_perf_baseline_scope ON erp_perf_baseline(organization_id,result,recorded_at);
CREATE INDEX IF NOT EXISTS ix_perf_load_scope ON erp_perf_load_run(organization_id,result,recorded_at);
CREATE INDEX IF NOT EXISTS ix_perf_hotspot_scope ON erp_perf_hotspot(organization_id,status,severity,recorded_at);
CREATE INDEX IF NOT EXISTS ix_perf_capacity_scope ON erp_perf_capacity(organization_id,result,recorded_at);
CREATE INDEX IF NOT EXISTS ix_perf_regression_scope ON erp_perf_regression(organization_id,result,recorded_at);
INSERT INTO erp_permissions(permission_id,permission_name) VALUES('performance.scalability.view','View performance, load testing and scalability controls') ON CONFLICT(permission_id) DO NOTHING;
INSERT INTO erp_permissions(permission_id,permission_name) VALUES('performance.scalability.manage','Manage performance, load testing and scalability controls') ON CONFLICT(permission_id) DO NOTHING;
INSERT INTO erp_role_permissions(role_id,permission_id) VALUES('super_admin','performance.scalability.view') ON CONFLICT(role_id,permission_id) DO NOTHING;
INSERT INTO erp_role_permissions(role_id,permission_id) VALUES('super_admin','performance.scalability.manage') ON CONFLICT(role_id,permission_id) DO NOTHING;
