-- V90.fz: Performance optimization execution, capacity remediation and scalability certification.
CREATE TABLE IF NOT EXISTS erp_perf_optimization_action(action_id TEXT PRIMARY KEY,organization_id TEXT NULL,finding_ref TEXT NOT NULL,action_type TEXT NOT NULL,title TEXT NOT NULL,owner_user_id TEXT NULL,due_date TEXT NULL,expected_latency_delta_pct DOUBLE PRECISION NULL,expected_throughput_delta_pct DOUBLE PRECISION NULL,expected_error_rate_delta_pct DOUBLE PRECISION NULL,status TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_capacity_remediation(remediation_id TEXT PRIMARY KEY,organization_id TEXT NULL,finding_ref TEXT NOT NULL,resource_type TEXT NOT NULL,current_value DOUBLE PRECISION NOT NULL,target_value DOUBLE PRECISION NOT NULL,unit TEXT NOT NULL,action_ref TEXT NOT NULL,status TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_optimization_result(result_id TEXT PRIMARY KEY,organization_id TEXT NULL,action_ref TEXT NOT NULL,baseline_ref TEXT NOT NULL,post_change_ref TEXT NOT NULL,latency_delta_pct DOUBLE PRECISION NOT NULL,throughput_delta_pct DOUBLE PRECISION NOT NULL,error_rate_delta_pct DOUBLE PRECISION NOT NULL,result TEXT NOT NULL,evidence_ref TEXT NULL,notes TEXT NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_perf_scalability_certification(certification_id TEXT PRIMARY KEY,organization_id TEXT NULL,period_key TEXT NOT NULL,result TEXT NOT NULL,certification_note TEXT NOT NULL,evidence_ref TEXT NOT NULL,certified_by TEXT NOT NULL,certified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,period_key));
CREATE TABLE IF NOT EXISTS erp_perf_optimization_period_close(close_id TEXT PRIMARY KEY,organization_id TEXT NULL,period_key TEXT NOT NULL,signoff_note TEXT NOT NULL,evidence_ref TEXT NOT NULL,closed_by TEXT NOT NULL,closed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,period_key));
CREATE INDEX IF NOT EXISTS ix_perf_opt_action_scope ON erp_perf_optimization_action(organization_id,status,created_at);
CREATE INDEX IF NOT EXISTS ix_perf_capacity_remediation_scope ON erp_perf_capacity_remediation(organization_id,status,created_at);
CREATE INDEX IF NOT EXISTS ix_perf_opt_result_scope ON erp_perf_optimization_result(organization_id,result,recorded_at);
CREATE INDEX IF NOT EXISTS ix_perf_cert_scope ON erp_perf_scalability_certification(organization_id,result,certified_at);
INSERT INTO erp_permissions(permission_id,permission_name) VALUES('performance.optimization.view','View performance optimization and scalability certification controls') ON CONFLICT(permission_id) DO NOTHING;
INSERT INTO erp_permissions(permission_id,permission_name) VALUES('performance.optimization.manage','Manage performance optimization and scalability certification controls') ON CONFLICT(permission_id) DO NOTHING;
INSERT INTO erp_role_permissions(role_id,permission_id) VALUES('super_admin','performance.optimization.view') ON CONFLICT(role_id,permission_id) DO NOTHING;
INSERT INTO erp_role_permissions(role_id,permission_id) VALUES('super_admin','performance.optimization.manage') ON CONFLICT(role_id,permission_id) DO NOTHING;
