-- FILE PATH: migrations/274_v90gx_company_gst_invoicing.sql
-- V90.gx (Session CS2): Company X/Y legal profile, FY document series, GST invoice detail, e-way thresholds, customer advance terms.
-- Same DDL as the runtime ensure_* function in the matching app/v90gx_*.py module (idempotent).
CREATE TABLE IF NOT EXISTS erp_entity_profile(entity_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,legal_name TEXT NOT NULL,trade_name TEXT NULL,business_role TEXT NOT NULL,gstin TEXT NULL,pan TEXT NULL,cin TEXT NULL,fssai_license_no TEXT NULL,fssai_valid_to DATE NULL,address_line1 TEXT NOT NULL,address_line2 TEXT NULL,city TEXT NOT NULL,district TEXT NULL,state_code TEXT NOT NULL,state_name TEXT NOT NULL,pincode TEXT NOT NULL,phone TEXT NULL,email TEXT NULL,bank_name TEXT NULL,bank_account_no TEXT NULL,bank_ifsc TEXT NULL,bank_branch TEXT NULL,upi_id TEXT NULL,invoice_prefix TEXT NULL,einvoice_applicable INTEGER NOT NULL DEFAULT 0,updated_by TEXT NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_document_series(series_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,doc_type TEXT NOT NULL,fy_code TEXT NOT NULL,prefix TEXT NOT NULL,next_no INTEGER NOT NULL DEFAULT 1,pad_width INTEGER NOT NULL DEFAULT 4,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(entity_id,doc_type,fy_code));
CREATE TABLE IF NOT EXISTS erp_document_number_log(log_id TEXT PRIMARY KEY,series_id TEXT NOT NULL,document_no TEXT NOT NULL,doc_date DATE NOT NULL,reference_type TEXT NULL,reference_id TEXT NULL,allocated_by TEXT NOT NULL,allocated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(series_id,document_no));
CREATE TABLE IF NOT EXISTS sales_invoice_gst_detail(invoice_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,seller_entity_id TEXT NOT NULL,invoice_date DATE NOT NULL,seller_gstin TEXT NULL,seller_state_code TEXT NULL,buyer_customer_id TEXT NULL,buyer_name TEXT NULL,buyer_gstin TEXT NULL,buyer_state_code TEXT NULL,place_of_supply TEXT NULL,supply_type TEXT NOT NULL,taxable_value NUMERIC NOT NULL DEFAULT 0,cgst_amount NUMERIC NOT NULL DEFAULT 0,sgst_amount NUMERIC NOT NULL DEFAULT 0,igst_amount NUMERIC NOT NULL DEFAULT 0,invoice_value NUMERIC NOT NULL DEFAULT 0,eway_required INTEGER NOT NULL DEFAULT 0,eway_threshold NUMERIC NOT NULL DEFAULT 0,eway_bill_no TEXT NULL,eway_valid_upto TEXT NULL,vehicle_no TEXT NULL,einvoice_status TEXT NOT NULL DEFAULT 'NOT_APPLICABLE',irn TEXT NULL,ack_no TEXT NULL,ack_date TEXT NULL,signed_qr TEXT NULL,fssai_license_no TEXT NULL,amount_in_words TEXT NOT NULL,finalized_by TEXT NOT NULL,finalized_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_eway_rule(rule_id TEXT PRIMARY KEY,seller_state_code TEXT NOT NULL UNIQUE,intra_state_threshold NUMERIC NOT NULL,inter_state_threshold NUMERIC NOT NULL,notes TEXT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS customer_payment_terms(customer_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,terms_type TEXT NOT NULL DEFAULT 'STANDARD',advance_pct NUMERIC NOT NULL DEFAULT 0,balance_days INTEGER NOT NULL DEFAULT 0,notes TEXT NULL,updated_by TEXT NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sales_order_advance(advance_id TEXT PRIMARY KEY,sales_order_id TEXT NOT NULL,organization_id TEXT NOT NULL,amount NUMERIC NOT NULL,mode TEXT NOT NULL,reference_no TEXT NOT NULL,received_on DATE NOT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(sales_order_id,reference_no));
CREATE INDEX IF NOT EXISTS ix_entity_profile_org ON erp_entity_profile(organization_id,business_role);
CREATE INDEX IF NOT EXISTS ix_invoice_gst_scope ON sales_invoice_gst_detail(organization_id,seller_entity_id,invoice_date);
CREATE INDEX IF NOT EXISTS ix_so_advance_order ON sales_order_advance(sales_order_id);
INSERT INTO erp_eway_rule(rule_id,seller_state_code,intra_state_threshold,inter_state_threshold,notes) VALUES('v90gx-eway-default','*',50000,50000,'Seeded default (V90.gx); verify against current state notification before go-live') ON CONFLICT(seller_state_code) DO NOTHING;
INSERT INTO erp_eway_rule(rule_id,seller_state_code,intra_state_threshold,inter_state_threshold,notes) VALUES('v90gx-eway-27','27',100000,50000,'Seeded default (V90.gx); verify against current state notification before go-live') ON CONFLICT(seller_state_code) DO NOTHING;
