-- FILE PATH: migrations/275_v90gx_intercompany_settlement.sql
-- V90.gx (Session CS2): Intercompany X to Y transfer-price policy, pricing, X invoice, Y receipt, settlement.
-- Same DDL as the runtime ensure_* function in the matching app/v90gx_*.py module (idempotent).
CREATE TABLE IF NOT EXISTS intercompany_transfer_price_policy(policy_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,from_entity_id TEXT NOT NULL,to_entity_id TEXT NOT NULL,item_master_id TEXT NULL,method TEXT NOT NULL,markup_pct NUMERIC NULL,fixed_price NUMERIC NULL,discount_pct NUMERIC NULL,gst_rate NUMERIC NOT NULL,effective_from DATE NOT NULL,effective_to DATE NULL,agreement_ref TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,closed_by TEXT NULL,closed_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS intercompany_pricing(transaction_id TEXT PRIMARY KEY,pricing_date DATE NOT NULL,supply_type TEXT NOT NULL,taxable_value NUMERIC NOT NULL,cgst_amount NUMERIC NOT NULL DEFAULT 0,sgst_amount NUMERIC NOT NULL DEFAULT 0,igst_amount NUMERIC NOT NULL DEFAULT 0,total_value NUMERIC NOT NULL,priced_by TEXT NOT NULL,priced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS intercompany_pricing_line(line_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,policy_id TEXT NOT NULL,method TEXT NOT NULL,basis_value NUMERIC NOT NULL,unit_price NUMERIC NOT NULL,taxable_value NUMERIC NOT NULL,gst_rate NUMERIC NOT NULL,tax_value NUMERIC NOT NULL);
CREATE TABLE IF NOT EXISTS intercompany_invoice(ic_invoice_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL UNIQUE,organization_id TEXT NOT NULL,from_entity_id TEXT NOT NULL,to_entity_id TEXT NOT NULL,invoice_no TEXT NOT NULL,invoice_date DATE NOT NULL,supply_type TEXT NOT NULL,taxable_value NUMERIC NOT NULL,cgst_amount NUMERIC NOT NULL DEFAULT 0,sgst_amount NUMERIC NOT NULL DEFAULT 0,igst_amount NUMERIC NOT NULL DEFAULT 0,total_value NUMERIC NOT NULL,settled_value NUMERIC NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ISSUED',eway_bill_no TEXT NULL,vehicle_no TEXT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(from_entity_id,invoice_no));
CREATE TABLE IF NOT EXISTS intercompany_receipt(receipt_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL UNIQUE,received_by TEXT NOT NULL,received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,shortage_qty NUMERIC NOT NULL DEFAULT 0,shortage_value NUMERIC NOT NULL DEFAULT 0,shortage_reason TEXT NULL,evidence_note TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS intercompany_receipt_line(receipt_line_id TEXT PRIMARY KEY,receipt_id TEXT NOT NULL,line_id TEXT NOT NULL,dispatched_qty NUMERIC NOT NULL,received_qty NUMERIC NOT NULL,shortage_qty NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS intercompany_settlement(settlement_id TEXT PRIMARY KEY,ic_invoice_id TEXT NOT NULL,organization_id TEXT NOT NULL,amount NUMERIC NOT NULL,mode TEXT NOT NULL,reference_no TEXT NOT NULL,settlement_date DATE NOT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(ic_invoice_id,reference_no));
CREATE INDEX IF NOT EXISTS ix_ic_policy_pair ON intercompany_transfer_price_policy(organization_id,from_entity_id,to_entity_id,status);
CREATE INDEX IF NOT EXISTS ix_ic_invoice_scope ON intercompany_invoice(organization_id,from_entity_id,to_entity_id,status);
