-- FILE PATH: migrations/277_v90gx_plant_operations.sql
-- V90.gx (Session CS2): Plant registers (oil, fuel, utilities, cartons), customer complaints, purchase returns.
-- Same DDL as the runtime ensure_* function in the matching app/v90gx_*.py module (idempotent).
CREATE TABLE IF NOT EXISTS plant_oil_log(log_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,location_id TEXT NOT NULL,business_date DATE NOT NULL,shift_code TEXT NULL,notes TEXT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,fryer_id TEXT NOT NULL,oil_item_id TEXT NULL,batch_id TEXT NULL,opening_litres NUMERIC NOT NULL,topped_up_litres NUMERIC NOT NULL DEFAULT 0,discarded_litres NUMERIC NOT NULL DEFAULT 0,closing_litres NUMERIC NOT NULL,consumed_litres NUMERIC NOT NULL,frying_temp_c NUMERIC NULL,tpm_pct NUMERIC NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS plant_fuel_log(log_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,location_id TEXT NOT NULL,business_date DATE NOT NULL,shift_code TEXT NULL,notes TEXT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,fuel_type TEXT NOT NULL,machine_id TEXT NULL,quantity NUMERIC NOT NULL,uom TEXT NOT NULL,rate NUMERIC NOT NULL DEFAULT 0,amount NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS plant_utility_log(log_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,location_id TEXT NOT NULL,business_date DATE NOT NULL,shift_code TEXT NULL,notes TEXT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,utility_type TEXT NOT NULL,meter_id TEXT NOT NULL,opening_reading NUMERIC NOT NULL,closing_reading NUMERIC NOT NULL,units NUMERIC NOT NULL,rate NUMERIC NOT NULL DEFAULT 0,amount NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS packing_carton_consumption(record_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,location_id TEXT NOT NULL,business_date DATE NOT NULL,shift_code TEXT NULL,notes TEXT NULL,recorded_by TEXT NOT NULL,recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,packing_run_id TEXT NULL,sku_id TEXT NOT NULL,carton_item_id TEXT NULL,packs_packed INTEGER NOT NULL,packs_per_carton INTEGER NOT NULL,expected_cartons INTEGER NOT NULL,cartons_used INTEGER NOT NULL,variance_cartons INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS customer_complaint(complaint_id TEXT PRIMARY KEY,complaint_no TEXT NOT NULL,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,customer_id TEXT NULL,customer_name TEXT NOT NULL,contact_phone TEXT NULL,sku_id TEXT NULL,lot_code TEXT NULL,complaint_date DATE NOT NULL,category TEXT NOT NULL,severity TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',assigned_to TEXT NULL,root_cause TEXT NULL,action_taken TEXT NULL,capa_ref TEXT NULL,customer_informed INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,closed_by TEXT NULL,closed_at TIMESTAMP NULL,UNIQUE(entity_id,complaint_no));
CREATE TABLE IF NOT EXISTS purchase_return(return_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,entity_id TEXT NOT NULL,location_id TEXT NOT NULL,warehouse_id TEXT NOT NULL,supplier_id TEXT NOT NULL,grn_id TEXT NULL,reason TEXT NOT NULL,reason_note TEXT NULL,status TEXT NOT NULL DEFAULT 'DRAFT',taxable_value NUMERIC NOT NULL DEFAULT 0,gst_value NUMERIC NOT NULL DEFAULT 0,total_value NUMERIC NOT NULL DEFAULT 0,debit_note_no TEXT NULL,created_by TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,posted_by TEXT NULL,posted_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS purchase_return_line(line_id TEXT PRIMARY KEY,return_id TEXT NOT NULL,item_master_id TEXT NOT NULL,lot_id TEXT NULL,quantity NUMERIC NOT NULL,uom TEXT NOT NULL,rate NUMERIC NOT NULL,gst_rate NUMERIC NOT NULL DEFAULT 0,taxable_value NUMERIC NOT NULL,gst_value NUMERIC NOT NULL);
CREATE INDEX IF NOT EXISTS ix_oil_log_scope ON plant_oil_log(entity_id,location_id,business_date);
CREATE INDEX IF NOT EXISTS ix_fuel_log_scope ON plant_fuel_log(entity_id,location_id,business_date);
CREATE INDEX IF NOT EXISTS ix_utility_log_scope ON plant_utility_log(entity_id,location_id,business_date);
CREATE INDEX IF NOT EXISTS ix_complaint_scope ON customer_complaint(entity_id,status,complaint_date);
CREATE INDEX IF NOT EXISTS ix_purchase_return_scope ON purchase_return(entity_id,status,supplier_id);
